# Generated by Django 5.1.1 on 2024-12-09 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerHeadShot',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(default='N/A', max_length=100)),
                ('player_image_url', models.URLField(default='https://via.placeholder.com/150')),
                ('background_colour', models.CharField(blank=True, default='#FFFFFF', max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(unique=True)),
                ('player_name', models.CharField(max_length=100)),
                ('stats', models.JSONField(blank=True, null=True)),
                ('ppg', models.FloatField(blank=True, null=True)),
                ('rpg', models.FloatField(blank=True, null=True)),
                ('apg', models.FloatField(blank=True, null=True)),
                ('spg', models.FloatField(blank=True, null=True)),
                ('bpg', models.FloatField(blank=True, null=True)),
                ('tovpg', models.FloatField(blank=True, null=True)),
                ('fg_pct', models.FloatField(blank=True, null=True)),
                ('ft_pct', models.FloatField(blank=True, null=True)),
                ('three_pt_pct', models.FloatField(blank=True, null=True)),
                ('point_total', models.IntegerField(blank=True, null=True)),
                ('rebound_total', models.IntegerField(blank=True, null=True)),
                ('assist_total', models.IntegerField(blank=True, null=True)),
                ('steal_total', models.IntegerField(blank=True, null=True)),
                ('block_total', models.IntegerField(blank=True, null=True)),
                ('turnover_total', models.IntegerField(blank=True, null=True)),
                ('seasons_played', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nba_stats.playerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('ppg', models.FloatField(blank=True, null=True)),
                ('rpg', models.FloatField(blank=True, null=True)),
                ('apg', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statsnapshots', to='nba_stats.playerprofile')),
            ],
        ),
    ]
